# Form implementation generated from reading ui file 'fittingroom.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(999, 878)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: rgb(22, 26, 48);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_7 = QtWidgets.QWidget(parent=self.widget)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(337, 75))
        self.widget_2.setStyleSheet("border: 4px solid rgb(15, 76, 117);\n"
"border-top-left-radius :7px;\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(-1, 11, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pictureModeBtn = QtWidgets.QPushButton(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pictureModeBtn.sizePolicy().hasHeightForWidth())
        self.pictureModeBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pictureModeBtn.setFont(font)
        self.pictureModeBtn.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-color: rgb(187, 225, 250);\n"
"border: 2px solid rgb(187, 225, 250);\n"
"border-top-left-radius :7px;\n"
"background-color: rgb(187, 225, 250);\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/image.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pictureModeBtn.setIcon(icon)
        self.pictureModeBtn.setIconSize(QtCore.QSize(45, 45))
        self.pictureModeBtn.setCheckable(True)
        self.pictureModeBtn.setObjectName("pictureModeBtn")
        self.horizontalLayout.addWidget(self.pictureModeBtn)
        self.cameraModeBtn = QtWidgets.QPushButton(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraModeBtn.sizePolicy().hasHeightForWidth())
        self.cameraModeBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.cameraModeBtn.setFont(font)
        self.cameraModeBtn.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-color: rgb(187, 225, 250);\n"
"border: 2px solid rgb(187, 225, 250);\n"
"border-top-left-radius :7px;\n"
"background-color: rgb(187, 225, 250);\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/photo-camera.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.cameraModeBtn.setIcon(icon1)
        self.cameraModeBtn.setIconSize(QtCore.QSize(45, 45))
        self.cameraModeBtn.setCheckable(True)
        self.cameraModeBtn.setObjectName("cameraModeBtn")
        self.horizontalLayout.addWidget(self.cameraModeBtn)
        self.horizontalLayout_3.addWidget(self.widget_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.widget_8 = QtWidgets.QWidget(parent=self.widget_7)
        self.widget_8.setStyleSheet("border: 4px solid rgb(15, 76, 117);\n"
"border-top-left-radius :7px;\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pencilStyleBtn = QtWidgets.QPushButton(parent=self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pencilStyleBtn.sizePolicy().hasHeightForWidth())
        self.pencilStyleBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pencilStyleBtn.setFont(font)
        self.pencilStyleBtn.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-color: rgb(187, 225, 250);\n"
"border: 2px solid rgb(187, 225, 250);\n"
"border-top-left-radius :7px;\n"
"background-color: rgb(187, 225, 250);\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/pencil.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pencilStyleBtn.setIcon(icon2)
        self.pencilStyleBtn.setIconSize(QtCore.QSize(45, 45))
        self.pencilStyleBtn.setCheckable(True)
        self.pencilStyleBtn.setObjectName("pencilStyleBtn")
        self.horizontalLayout_4.addWidget(self.pencilStyleBtn)
        self.cartoonStyleBtn = QtWidgets.QPushButton(parent=self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cartoonStyleBtn.sizePolicy().hasHeightForWidth())
        self.cartoonStyleBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.cartoonStyleBtn.setFont(font)
        self.cartoonStyleBtn.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-color: rgb(187, 225, 250);\n"
"border: 2px solid rgb(187, 225, 250);\n"
"border-top-left-radius :7px;\n"
"background-color: rgb(187, 225, 250);\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/film.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.cartoonStyleBtn.setIcon(icon3)
        self.cartoonStyleBtn.setIconSize(QtCore.QSize(45, 45))
        self.cartoonStyleBtn.setCheckable(True)
        self.cartoonStyleBtn.setObjectName("cartoonStyleBtn")
        self.horizontalLayout_4.addWidget(self.cartoonStyleBtn)
        self.horizontalLayout_3.addWidget(self.widget_8)
        self.verticalLayout_2.addWidget(self.widget_7)
        self.widget_3 = QtWidgets.QWidget(parent=self.widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(0, 8, 0, 0)
        self.horizontalLayout_2.setSpacing(12)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.imageArea = QtWidgets.QScrollArea(parent=self.widget_3)
        self.imageArea.setStyleSheet("border: 4px solid rgb(15, 76, 117);\n"
"border-top-left-radius :7px;\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        self.imageArea.setLineWidth(0)
        self.imageArea.setWidgetResizable(True)
        self.imageArea.setObjectName("imageArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 674, 711))
        self.scrollAreaWidgetContents.setStyleSheet("border: 4px solid rgb(15, 76, 117);\n"
"border-top-left-radius :7px;\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.imageLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageLabel.sizePolicy().hasHeightForWidth())
        self.imageLabel.setSizePolicy(sizePolicy)
        self.imageLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.imageLabel.setStyleSheet("background-color: rgb(205, 245, 253);\n"
"border: 0px;")
        self.imageLabel.setText("")
        self.imageLabel.setIndent(-1)
        self.imageLabel.setObjectName("imageLabel")
        self.verticalLayout_4.addWidget(self.imageLabel)
        self.imageArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.imageArea)
        self.widget_4 = QtWidgets.QWidget(parent=self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMinimumSize(QtCore.QSize(200, 0))
        self.widget_4.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_5 = QtWidgets.QWidget(parent=self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setStyleSheet("border: 4px solid rgb(15, 76, 117);\n"
"border-top-left-radius :7px;\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_5.setSpacing(8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.selectClothbtn = QtWidgets.QPushButton(parent=self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectClothbtn.sizePolicy().hasHeightForWidth())
        self.selectClothbtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.selectClothbtn.setFont(font)
        self.selectClothbtn.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-color: rgb(187, 225, 250);\n"
"border: 2px solid rgb(187, 225, 250);\n"
"border-top-left-radius :7px;\n"
"background-color: rgb(187, 225, 250);\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/tshirt.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.selectClothbtn.setIcon(icon4)
        self.selectClothbtn.setIconSize(QtCore.QSize(40, 40))
        self.selectClothbtn.setObjectName("selectClothbtn")
        self.verticalLayout_5.addWidget(self.selectClothbtn)
        self.clothlabel = QtWidgets.QLabel(parent=self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clothlabel.sizePolicy().hasHeightForWidth())
        self.clothlabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.clothlabel.setFont(font)
        self.clothlabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px;")
        self.clothlabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.clothlabel.setObjectName("clothlabel")
        self.verticalLayout_5.addWidget(self.clothlabel)
        self.clothSizeSlider = QtWidgets.QSlider(parent=self.widget_5)
        self.clothSizeSlider.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px;")
        self.clothSizeSlider.setMaximum(200)
        self.clothSizeSlider.setSingleStep(1)
        self.clothSizeSlider.setProperty("value", 100)
        self.clothSizeSlider.setSliderPosition(100)
        self.clothSizeSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.clothSizeSlider.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBelow)
        self.clothSizeSlider.setTickInterval(10)
        self.clothSizeSlider.setObjectName("clothSizeSlider")
        self.verticalLayout_5.addWidget(self.clothSizeSlider)
        self.clothCheckBox = QtWidgets.QCheckBox(parent=self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.clothCheckBox.setFont(font)
        self.clothCheckBox.setStyleSheet("background-color: rgb(187, 225, 250);")
        self.clothCheckBox.setChecked(True)
        self.clothCheckBox.setObjectName("clothCheckBox")
        self.verticalLayout_5.addWidget(self.clothCheckBox)
        self.line = QtWidgets.QFrame(parent=self.widget_5)
        self.line.setStyleSheet("background-color: rgb(22, 26, 48);\n"
"border-color: rgb(22, 26, 48);\n"
"color: rgb(22, 26, 48);")
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.selectPantsbtn = QtWidgets.QPushButton(parent=self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectPantsbtn.sizePolicy().hasHeightForWidth())
        self.selectPantsbtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.selectPantsbtn.setFont(font)
        self.selectPantsbtn.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-color: rgb(187, 225, 250);\n"
"border: 2px solid rgb(187, 225, 250);\n"
"border-top-left-radius :7px;\n"
"background-color: rgb(187, 225, 250);\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/jeans.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.selectPantsbtn.setIcon(icon5)
        self.selectPantsbtn.setIconSize(QtCore.QSize(40, 40))
        self.selectPantsbtn.setObjectName("selectPantsbtn")
        self.verticalLayout_5.addWidget(self.selectPantsbtn)
        self.pantslabel = QtWidgets.QLabel(parent=self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pantslabel.sizePolicy().hasHeightForWidth())
        self.pantslabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pantslabel.setFont(font)
        self.pantslabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px;")
        self.pantslabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pantslabel.setObjectName("pantslabel")
        self.verticalLayout_5.addWidget(self.pantslabel)
        self.pantSizeSlider = QtWidgets.QSlider(parent=self.widget_5)
        self.pantSizeSlider.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px;")
        self.pantSizeSlider.setMaximum(200)
        self.pantSizeSlider.setProperty("value", 100)
        self.pantSizeSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.pantSizeSlider.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBelow)
        self.pantSizeSlider.setTickInterval(10)
        self.pantSizeSlider.setObjectName("pantSizeSlider")
        self.verticalLayout_5.addWidget(self.pantSizeSlider)
        self.pantsCheckBox = QtWidgets.QCheckBox(parent=self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pantsCheckBox.setFont(font)
        self.pantsCheckBox.setStyleSheet("background-color: rgb(187, 225, 250);")
        self.pantsCheckBox.setChecked(True)
        self.pantsCheckBox.setObjectName("pantsCheckBox")
        self.verticalLayout_5.addWidget(self.pantsCheckBox)
        self.line_2 = QtWidgets.QFrame(parent=self.widget_5)
        self.line_2.setStyleSheet("background-color: rgb(22, 26, 48);\n"
"border-color: rgb(22, 26, 48);\n"
"color: rgb(22, 26, 48);")
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_5.addWidget(self.line_2)
        self.selectSunglassesbtn = QtWidgets.QPushButton(parent=self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectSunglassesbtn.sizePolicy().hasHeightForWidth())
        self.selectSunglassesbtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.selectSunglassesbtn.setFont(font)
        self.selectSunglassesbtn.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-color: rgb(187, 225, 250);\n"
"border: 2px solid rgb(187, 225, 250);\n"
"border-top-left-radius :7px;\n"
"background-color: rgb(187, 225, 250);\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon/sunglasses.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.selectSunglassesbtn.setIcon(icon6)
        self.selectSunglassesbtn.setIconSize(QtCore.QSize(50, 50))
        self.selectSunglassesbtn.setObjectName("selectSunglassesbtn")
        self.verticalLayout_5.addWidget(self.selectSunglassesbtn)
        self.sunglasseslabel = QtWidgets.QLabel(parent=self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sunglasseslabel.sizePolicy().hasHeightForWidth())
        self.sunglasseslabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sunglasseslabel.setFont(font)
        self.sunglasseslabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px;")
        self.sunglasseslabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sunglasseslabel.setObjectName("sunglasseslabel")
        self.verticalLayout_5.addWidget(self.sunglasseslabel)
        self.sunglassessize = QtWidgets.QSlider(parent=self.widget_5)
        self.sunglassessize.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px;")
        self.sunglassessize.setMaximum(200)
        self.sunglassessize.setPageStep(10)
        self.sunglassessize.setProperty("value", 100)
        self.sunglassessize.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.sunglassessize.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBelow)
        self.sunglassessize.setTickInterval(10)
        self.sunglassessize.setObjectName("sunglassessize")
        self.verticalLayout_5.addWidget(self.sunglassessize)
        self.sunglassesCheckBox = QtWidgets.QCheckBox(parent=self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sunglassesCheckBox.setFont(font)
        self.sunglassesCheckBox.setStyleSheet("background-color: rgb(187, 225, 250);")
        self.sunglassesCheckBox.setChecked(True)
        self.sunglassesCheckBox.setObjectName("sunglassesCheckBox")
        self.verticalLayout_5.addWidget(self.sunglassesCheckBox)
        self.verticalLayout_3.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(parent=self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 136))
        self.widget_6.setStyleSheet("border: 4px solid rgb(15, 76, 117);\n"
"border-top-left-radius :7px;\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.selectBGBtn = QtWidgets.QPushButton(parent=self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectBGBtn.sizePolicy().hasHeightForWidth())
        self.selectBGBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.selectBGBtn.setFont(font)
        self.selectBGBtn.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-color: rgb(187, 225, 250);\n"
"border: 2px solid rgb(187, 225, 250);\n"
"border-top-left-radius :7px;\n"
"background-color: rgb(187, 225, 250);\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icon/background.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.selectBGBtn.setIcon(icon7)
        self.selectBGBtn.setIconSize(QtCore.QSize(50, 50))
        self.selectBGBtn.setObjectName("selectBGBtn")
        self.verticalLayout_6.addWidget(self.selectBGBtn)
        self.BGcheckbox = QtWidgets.QCheckBox(parent=self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BGcheckbox.sizePolicy().hasHeightForWidth())
        self.BGcheckbox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BGcheckbox.setFont(font)
        self.BGcheckbox.setStyleSheet("background-color: rgb(187, 225, 250);")
        self.BGcheckbox.setObjectName("BGcheckbox")
        self.verticalLayout_6.addWidget(self.BGcheckbox)
        self.verticalLayout_3.addWidget(self.widget_6)
        self.horizontalLayout_2.addWidget(self.widget_4)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FittingRoom"))
        self.pictureModeBtn.setText(_translate("MainWindow", "相片模式\n"
"Picture Mode"))
        self.cameraModeBtn.setText(_translate("MainWindow", "鏡頭模式\n"
"Camera Mode"))
        self.pencilStyleBtn.setText(_translate("MainWindow", "鉛筆風格"))
        self.cartoonStyleBtn.setText(_translate("MainWindow", "卡通風格"))
        self.selectClothbtn.setText(_translate("MainWindow", "選擇上衣"))
        self.clothlabel.setText(_translate("MainWindow", "調整上衣尺寸(100%)"))
        self.clothCheckBox.setText(_translate("MainWindow", "顯示上衣"))
        self.selectPantsbtn.setText(_translate("MainWindow", "選擇下著"))
        self.pantslabel.setText(_translate("MainWindow", "調整下著尺寸(100%)"))
        self.pantsCheckBox.setText(_translate("MainWindow", "顯示下著"))
        self.selectSunglassesbtn.setText(_translate("MainWindow", "選擇眼鏡"))
        self.sunglasseslabel.setText(_translate("MainWindow", "調整眼鏡尺寸(100%)"))
        self.sunglassesCheckBox.setText(_translate("MainWindow", "顯示眼鏡"))
        self.selectBGBtn.setText(_translate("MainWindow", "選擇背景"))
        self.BGcheckbox.setText(_translate("MainWindow", "替換背景"))
