# Form implementation generated from reading ui file 'fittingroom.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_fittingRoom(object):
    def setupUi(self, fittingRoom):
        fittingRoom.setObjectName("fittingRoom")
        fittingRoom.resize(792, 600)
        fittingRoom.setStyleSheet("background-color: rgb(22, 26, 48);")
        self.centralwidget = QtWidgets.QWidget(parent=fittingRoom)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 431, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(23)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=self.horizontalLayoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pictureModeBtn = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pictureModeBtn.sizePolicy().hasHeightForWidth())
        self.pictureModeBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pictureModeBtn.setFont(font)
        self.pictureModeBtn.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"Consolas\";\n"
"border-color: rgb(187, 225, 250);\n"
"border: 2px solid rgb(187, 225, 250);\n"
"border-top-left-radius :7px;\n"
"background-color: rgb(187, 225, 250);\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        self.pictureModeBtn.setObjectName("pictureModeBtn")
        self.horizontalLayout_4.addWidget(self.pictureModeBtn)
        self.cameraModeBtn = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraModeBtn.sizePolicy().hasHeightForWidth())
        self.cameraModeBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.cameraModeBtn.setFont(font)
        self.cameraModeBtn.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"Consolas\";\n"
"border-color: rgb(187, 225, 250);\n"
"border: 2px solid rgb(187, 225, 250);\n"
"border-top-left-radius :7px;\n"
"background-color: rgb(187, 225, 250);\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        self.cameraModeBtn.setObjectName("cameraModeBtn")
        self.horizontalLayout_4.addWidget(self.cameraModeBtn)
        self.horizontalLayout.addWidget(self.frame)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(29, 109, 751, 461))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(600, 0))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalSlider = QtWidgets.QSlider(parent=self.horizontalLayoutWidget_2)
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_2.addWidget(self.horizontalSlider)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"Consolas\";\n"
"border-color: rgb(187, 225, 250);\n"
"border: 2px solid rgb(187, 225, 250);\n"
"border-top-left-radius :7px;\n"
"background-color: rgb(187, 225, 250);\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"Consolas\";\n"
"border-color: rgb(187, 225, 250);\n"
"border: 2px solid rgb(187, 225, 250);\n"
"border-top-left-radius :7px;\n"
"background-color: rgb(187, 225, 250);\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_2.addWidget(self.pushButton_7)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"Consolas\";\n"
"border-color: rgb(187, 225, 250);\n"
"border: 2px solid rgb(187, 225, 250);\n"
"border-top-left-radius :7px;\n"
"background-color: rgb(187, 225, 250);\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"Consolas\";\n"
"border-color: rgb(187, 225, 250);\n"
"border: 2px solid rgb(187, 225, 250);\n"
"border-top-left-radius :7px;\n"
"background-color: rgb(187, 225, 250);\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_2.addWidget(self.pushButton_8)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"Consolas\";\n"
"border-color: rgb(187, 225, 250);\n"
"border: 2px solid rgb(187, 225, 250);\n"
"border-top-left-radius :7px;\n"
"background-color: rgb(187, 225, 250);\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.verticalLayout_2.setStretch(5, 1)
        self.verticalLayout_2.setStretch(6, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        fittingRoom.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=fittingRoom)
        self.statusbar.setObjectName("statusbar")
        fittingRoom.setStatusBar(self.statusbar)

        self.retranslateUi(fittingRoom)
        QtCore.QMetaObject.connectSlotsByName(fittingRoom)

    def retranslateUi(self, fittingRoom):
        _translate = QtCore.QCoreApplication.translate
        fittingRoom.setWindowTitle(_translate("fittingRoom", "Fitting Room"))
        self.pictureModeBtn.setText(_translate("fittingRoom", "相片模式\n"
"Picture Mode"))
        self.cameraModeBtn.setText(_translate("fittingRoom", "鏡頭模式\n"
"Camera Mode"))
        self.label_2.setText(_translate("fittingRoom", "調整衣服尺寸"))
        self.pushButton_4.setText(_translate("fittingRoom", "選擇上衣"))
        self.pushButton_7.setText(_translate("fittingRoom", "選擇下著"))
        self.pushButton_6.setText(_translate("fittingRoom", "選擇眼鏡"))
        self.pushButton_8.setText(_translate("fittingRoom", "PushButton"))
        self.pushButton_3.setText(_translate("fittingRoom", "PushButton"))
