# Form implementation generated from reading ui file 'fittingroom.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(22, 26, 48);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(337, 86))
        self.widget_2.setStyleSheet("border: 4px solid rgb(15, 76, 117);\n"
"border-top-left-radius :7px;\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(-1, 11, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pictureModeBtn = QtWidgets.QPushButton(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pictureModeBtn.sizePolicy().hasHeightForWidth())
        self.pictureModeBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pictureModeBtn.setFont(font)
        self.pictureModeBtn.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"Consolas\";\n"
"border-color: rgb(187, 225, 250);\n"
"border: 2px solid rgb(187, 225, 250);\n"
"border-top-left-radius :7px;\n"
"background-color: rgb(187, 225, 250);\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        self.pictureModeBtn.setCheckable(True)
        self.pictureModeBtn.setObjectName("pictureModeBtn")
        self.horizontalLayout.addWidget(self.pictureModeBtn)
        self.cameraModeBtn = QtWidgets.QPushButton(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraModeBtn.sizePolicy().hasHeightForWidth())
        self.cameraModeBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.cameraModeBtn.setFont(font)
        self.cameraModeBtn.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"Consolas\";\n"
"border-color: rgb(187, 225, 250);\n"
"border: 2px solid rgb(187, 225, 250);\n"
"border-top-left-radius :7px;\n"
"background-color: rgb(187, 225, 250);\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        self.cameraModeBtn.setCheckable(True)
        self.cameraModeBtn.setObjectName("cameraModeBtn")
        self.horizontalLayout.addWidget(self.cameraModeBtn)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(parent=self.widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(0, 8, 0, 0)
        self.horizontalLayout_2.setSpacing(12)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.imageArea = QtWidgets.QScrollArea(parent=self.widget_3)
        self.imageArea.setStyleSheet("border: 4px solid rgb(15, 76, 117);\n"
"border-top-left-radius :7px;\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        self.imageArea.setLineWidth(0)
        self.imageArea.setWidgetResizable(True)
        self.imageArea.setObjectName("imageArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 606, 423))
        self.scrollAreaWidgetContents.setStyleSheet("border: 4px solid rgb(15, 76, 117);\n"
"border-top-left-radius :7px;\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.imageLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageLabel.sizePolicy().hasHeightForWidth())
        self.imageLabel.setSizePolicy(sizePolicy)
        self.imageLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.imageLabel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 0px;")
        self.imageLabel.setText("")
        self.imageLabel.setIndent(-1)
        self.imageLabel.setObjectName("imageLabel")
        self.verticalLayout_4.addWidget(self.imageLabel)
        self.imageArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.imageArea)
        self.widget_4 = QtWidgets.QWidget(parent=self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMinimumSize(QtCore.QSize(130, 0))
        self.widget_4.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget_4.setStyleSheet("border: 4px solid rgb(15, 76, 117);\n"
"border-top-left-radius :7px;\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.selectClothbtn = QtWidgets.QPushButton(parent=self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectClothbtn.sizePolicy().hasHeightForWidth())
        self.selectClothbtn.setSizePolicy(sizePolicy)
        self.selectClothbtn.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"Consolas\";\n"
"border-color: rgb(187, 225, 250);\n"
"border: 2px solid rgb(187, 225, 250);\n"
"border-top-left-radius :7px;\n"
"background-color: rgb(187, 225, 250);\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        self.selectClothbtn.setObjectName("selectClothbtn")
        self.verticalLayout_3.addWidget(self.selectClothbtn)
        self.label_2 = QtWidgets.QLabel(parent=self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px;")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.clothSizeSlider = QtWidgets.QSlider(parent=self.widget_4)
        self.clothSizeSlider.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px;")
        self.clothSizeSlider.setMaximum(200)
        self.clothSizeSlider.setSingleStep(1)
        self.clothSizeSlider.setProperty("value", 100)
        self.clothSizeSlider.setSliderPosition(100)
        self.clothSizeSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.clothSizeSlider.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBelow)
        self.clothSizeSlider.setTickInterval(10)
        self.clothSizeSlider.setObjectName("clothSizeSlider")
        self.verticalLayout_3.addWidget(self.clothSizeSlider)
        self.selectPantsbtn = QtWidgets.QPushButton(parent=self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectPantsbtn.sizePolicy().hasHeightForWidth())
        self.selectPantsbtn.setSizePolicy(sizePolicy)
        self.selectPantsbtn.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"Consolas\";\n"
"border-color: rgb(187, 225, 250);\n"
"border: 2px solid rgb(187, 225, 250);\n"
"border-top-left-radius :7px;\n"
"background-color: rgb(187, 225, 250);\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        self.selectPantsbtn.setObjectName("selectPantsbtn")
        self.verticalLayout_3.addWidget(self.selectPantsbtn)
        self.label = QtWidgets.QLabel(parent=self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.pantSizeSlider = QtWidgets.QSlider(parent=self.widget_4)
        self.pantSizeSlider.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px;")
        self.pantSizeSlider.setMaximum(200)
        self.pantSizeSlider.setProperty("value", 100)
        self.pantSizeSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.pantSizeSlider.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBelow)
        self.pantSizeSlider.setTickInterval(10)
        self.pantSizeSlider.setObjectName("pantSizeSlider")
        self.verticalLayout_3.addWidget(self.pantSizeSlider)
        self.selectSunglassesbtn = QtWidgets.QPushButton(parent=self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectSunglassesbtn.sizePolicy().hasHeightForWidth())
        self.selectSunglassesbtn.setSizePolicy(sizePolicy)
        self.selectSunglassesbtn.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"Consolas\";\n"
"border-color: rgb(187, 225, 250);\n"
"border: 2px solid rgb(187, 225, 250);\n"
"border-top-left-radius :7px;\n"
"background-color: rgb(187, 225, 250);\n"
"border-top-right-radius : 7px;                  \n"
"border-bottom-left-radius : 7px;\n"
"border-bottom-right-radius : 7px")
        self.selectSunglassesbtn.setObjectName("selectSunglassesbtn")
        self.verticalLayout_3.addWidget(self.selectSunglassesbtn)
        self.label_3 = QtWidgets.QLabel(parent=self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px;")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.horizontalSlider_3 = QtWidgets.QSlider(parent=self.widget_4)
        self.horizontalSlider_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px;")
        self.horizontalSlider_3.setMaximum(200)
        self.horizontalSlider_3.setPageStep(10)
        self.horizontalSlider_3.setProperty("value", 100)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider_3.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBelow)
        self.horizontalSlider_3.setTickInterval(10)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.verticalLayout_3.addWidget(self.horizontalSlider_3)
        self.horizontalLayout_2.addWidget(self.widget_4)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FittingRoom"))
        self.pictureModeBtn.setText(_translate("MainWindow", "相片模式\n"
"Picture Mode"))
        self.cameraModeBtn.setText(_translate("MainWindow", "鏡頭模式\n"
"Camera Mode"))
        self.selectClothbtn.setText(_translate("MainWindow", "選擇上衣"))
        self.label_2.setText(_translate("MainWindow", "調整上衣尺寸"))
        self.selectPantsbtn.setText(_translate("MainWindow", "選擇下著"))
        self.label.setText(_translate("MainWindow", "調整下著尺寸"))
        self.selectSunglassesbtn.setText(_translate("MainWindow", "選擇眼鏡"))
        self.label_3.setText(_translate("MainWindow", "調整眼鏡尺寸"))
